apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: gcpsecretmanagers.platform.openco.tech
spec:
  group: platform.openco.tech
  names:
    kind: GCPSecretManager
    plural: gcpsecretmanagers
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                appName:
                  type: string
                projectId:
                  type: string
                replication:
                  type: string
                  enum: [automatic, user_managed]
                  default: "automatic"
                secrets:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                    required:
                      - name
                  default: []
              required:
                - appName
                - projectId
            status:
              type: object
              properties:
                ready:
                  type: boolean
