apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: gcpsecretmanagers.platform.openco.tech
spec:
  group: platform.openco.tech
  names:
    kind: GCPSecretManager
    plural: gcpsecretmanagers
  scope: Namespaced
  defaultCompositeDeletePolicy: Background
  defaultCompositionRef:
    name: gcpsecretmanager.platform.openco.tech
  defaultCompositionUpdatePolicy: Automatic
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                appName:
                  type: string
                projectId:
                  type: string
                replication:
                  type: string
                  enum: [automatic, user_managed]
                  default: "automatic"
                secrets:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                    required:
                      - name
                  default: []
              required:
                - appName
            status:
              type: object
              properties:
                message:
                  type: string
                  description: Human-readable status message including any errors
                ready:
                  type: boolean
      additionalPrinterColumns:
        - name: READY
          type: string
          jsonPath: .status.conditions[?(@.type=='Ready')].status
        - name: SYNCED
          type: string
          jsonPath: .status.conditions[?(@.type=='Synced')].status
        - name: MESSAGE
          type: string
          priority: 1
          jsonPath: .status.conditions[?(@.type=='Developer')].message
