apiVersion: platform.openco.tech/v1alpha1
kind: AppEnvironment
metadata:
  name: sequencer-test
  namespace: sre
spec:
  appName: sequencer-test
  environment: hml
  teamId: sre
  costCenter: CC-TEST-001
