apiVersion: platform.openco.tech/v1alpha1
kind: AppEnvironment
metadata:
  name: test-viktor-pattern
  namespace: demo
spec:
  appName: viktor-test
  environment: sandbox
  teamId: platform
  costCenter: "12345"
  cloudRun:
    enabled: true
    port: 8080
    public: false
  secretManager:
    enabled: true
    secrets: []
