apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcpsecretmanager.platform.openco.tech
spec:
  compositeTypeRef:
    apiVersion: platform.openco.tech/v1alpha1
    kind: GCPSecretManager
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: secret
            base:
              apiVersion: secretmanager.gcp.m.upbound.io/v1beta1
              kind: Secret
              spec:
                forProvider:
                  replication:
                    auto: {}
            patches:
              - fromFieldPath: spec.appName
                toFieldPath: metadata.name
              - fromFieldPath: spec.projectId
                toFieldPath: spec.forProvider.project

    - step: status-handler
      functionRef:
        name: function-status-transformer
      input:
        apiVersion: function-status-transformer.fn.crossplane.io/v1beta1
        kind: StatusTransformation
        statusConditionHooks:
           # Secret creation errors - Extract and pass upstream
           - matchers:
               - resources:
                   - name: "secret"
                 conditions:
                   - type: Synced
                     status: "False"
                     reason: ReconcileError
                     message: "(?P<ErrorMsg>.*)"
             setConditions:
               - target: CompositeAndClaim
                 force: true
                 condition:
                   type: Developer
                   status: "False"
                   reason: SecretCreationFailed
                   message: "Secret Manager creation failed: {{ .ErrorMsg }}"
             createEvents:
               - target: CompositeAndClaim
                 event:
                   type: Warning
                   reason: SecretCreationFailed
                   message: "Secret Manager secret creation failed"

           # Success condition - Secret ready
           - matchers:
               - resources:
                   - name: "secret"
                 conditions:
                   - type: Synced
                     status: "True"
                   - type: Ready
                     status: "True"
             setConditions:
               - target: CompositeAndClaim
                 force: false
                 condition:
                   type: Developer
                   status: "True"
                   reason: SecretReady
                   message: "Secret Manager secret successfully created"
             createEvents:
               - target: CompositeAndClaim
                 event:
                   type: Normal
                   reason: SecretReady
                   message: "Secret Manager secret successfully provisioned"

    - step: auto-ready
      functionRef:
        name: function-auto-ready
