apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcpidentity.platform.openco.tech
spec:
  compositeTypeRef:
    apiVersion: platform.openco.tech/v1alpha1
    kind: GCPIdentity
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: service-account
            base:
              apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
              kind: ServiceAccount
              spec:
                forProvider:
                  displayName: Service account for app
            patches:
              - fromFieldPath: spec.appName
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: 'sa-%s'
              - fromFieldPath: spec.projectId
                toFieldPath: spec.forProvider.project
              - fromFieldPath: spec.appName
                toFieldPath: spec.forProvider.displayName
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: 'Service account for %s'
              - fromFieldPath: spec.teamId
                toFieldPath: metadata.labels[team]
              - fromFieldPath: spec.environment
                toFieldPath: metadata.labels[env]
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.email
                toFieldPath: status.serviceAccountEmail
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.uniqueId
                toFieldPath: status.serviceAccountId

          - name: iam-binding
            base:
              apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
              kind: ProjectIAMMember
              spec:
                forProvider:
                  role: roles/run.invoker
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'sa-run-invoker-%s'
                toFieldPath: metadata.name
              - fromFieldPath: spec.projectId
                toFieldPath: spec.forProvider.project
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: status.serviceAccountEmail
                  strategy: string
                  string:
                    fmt: 'serviceAccount:%s'
                toFieldPath: spec.forProvider.member

    - step: status-handler
      functionRef:
        name: function-status-transformer
      input:
        apiVersion: function-status-transformer.fn.crossplane.io/v1beta1
        kind: StatusTransformation
        statusConditionHooks:
          # Service Account creation errors - Extract and pass upstream
          - matchers:
              - resources:
                  - name: "service-account"
                conditions:
                  - type: Synced
                    status: "False"
                    reason: ReconcileError
                    message: "(?P<ErrorMsg>.*)"
            setConditions:
              - target: CompositeAndClaim
                force: true
                condition:
                  type: Developer
                  status: "False"
                  reason: ServiceAccountFailed
                  message: "Service Account creation failed: {{ .ErrorMsg }}"
            createEvents:
              - target: CompositeAndClaim
                event:
                  type: Warning
                  reason: ServiceAccountFailed
                  message: "Service Account creation failed"

          # IAM binding errors - Extract and pass upstream
          - matchers:
              - resources:
                  - name: "iam-binding"
                conditions:
                  - type: Synced
                    status: "False"
                    reason: ReconcileError
                    message: "(?P<ErrorMsg>.*)"
            setConditions:
              - target: CompositeAndClaim
                force: true
                condition:
                  type: Developer
                  status: "False"
                  reason: IAMBindingFailed
                  message: "IAM binding failed: {{ .ErrorMsg }}"
            createEvents:
              - target: CompositeAndClaim
                event:
                  type: Warning
                  reason: IAMBindingFailed
                  message: "IAM binding failed"

          # Success condition - All resources synced and ready
          - matchers:
              - resources:
                  - name: "service-account"
                conditions:
                  - type: Synced
                    status: "True"
                  - type: Ready
                    status: "True"
              - resources:
                  - name: "iam-binding"
                conditions:
                  - type: Synced
                    status: "True"
                  - type: Ready
                    status: "True"
            setConditions:
              - target: CompositeAndClaim
                force: false
                condition:
                  type: Developer
                  status: "True"
                  reason: IdentityReady
                  message: "Service account and IAM bindings successfully configured"
            createEvents:
              - target: CompositeAndClaim
                event:
                  type: Normal
                  reason: IdentityReady
                  message: "Identity resources successfully provisioned"

    - step: auto-ready
      functionRef:
        name: function-auto-ready
