apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcpproject.platform.openco.tech
spec:
  compositeTypeRef:
    apiVersion: platform.openco.tech/v1alpha1
    kind: GCPProject
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: project
            base:
              apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
              kind: Project
              spec:
                forProvider:
                  autoCreateNetwork: false
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.environment
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'prj-%s-%s'
                toFieldPath: metadata.name
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.environment
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'prj-%s-%s'
                toFieldPath: spec.forProvider.name
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.environment
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'prj-%s-%s'
                toFieldPath: spec.forProvider.projectId
              - fromFieldPath: spec.billingAccount
                toFieldPath: spec.forProvider.billingAccount
              - fromFieldPath: spec.orgId
                toFieldPath: spec.forProvider.orgId
              - fromFieldPath: spec.environment
                toFieldPath: metadata.labels[env]
              - fromFieldPath: spec.teamId
                toFieldPath: metadata.labels[team]
              - fromFieldPath: spec.costCenter
                toFieldPath: metadata.labels[cost-center]
              - type: ToCompositeFieldPath
                fromFieldPath: spec.forProvider.projectId
                toFieldPath: status.projectId
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.number
                toFieldPath: status.projectNumber
              # Dynamic deletion policy: ABANDON for sandbox (fast iteration), DELETE for hml/prod (proper cleanup)
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.environment
                  strategy: string
                  string:
                    fmt: '%s'
                toFieldPath: spec.forProvider.deletionPolicy
                transforms:
                  - type: map
                    map:
                      sandbox: ABANDON
                      hml: DELETE
                      prod: DELETE

          - name: sharedvpc-service-project
            base:
              apiVersion: compute.gcp.m.upbound.io/v1beta1
              kind: SharedVPCServiceProject
              spec:
                forProvider: {}
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.environment
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'prj-%s-%s'
                toFieldPath: spec.forProvider.serviceProject
              - fromFieldPath: spec.environment
                toFieldPath: spec.forProvider.hostProject
                transforms:
                  - type: map
                    map:
                      hml: prj-networking-hmg-438117
                      prod: prj-networking-prd-438117
                      sandbox: prj-networking-sandbox-455812
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'svpc-link-%s'
                toFieldPath: metadata.name

          - name: compute-api
            base:
              apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
              kind: ProjectService
              spec:
                forProvider:
                  service: compute.googleapis.com
                  disableOnDestroy: false
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.environment
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'prj-%s-%s'
                toFieldPath: spec.forProvider.project
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'compute-api-%s'
                toFieldPath: metadata.name

          - name: run-api
            base:
              apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
              kind: ProjectService
              spec:
                forProvider:
                  service: run.googleapis.com
                  disableOnDestroy: false
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.environment
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'prj-%s-%s'
                toFieldPath: spec.forProvider.project
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'run-api-%s'
                toFieldPath: metadata.name

          - name: artifactregistry-api
            base:
              apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
              kind: ProjectService
              spec:
                forProvider:
                  service: artifactregistry.googleapis.com
                  disableOnDestroy: false
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.environment
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'prj-%s-%s'
                toFieldPath: spec.forProvider.project
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'artifactregistry-api-%s'
                toFieldPath: metadata.name

          - name: iam-api
            base:
              apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
              kind: ProjectService
              spec:
                forProvider:
                  service: iam.googleapis.com
                  disableOnDestroy: false
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.environment
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'prj-%s-%s'
                toFieldPath: spec.forProvider.project
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'iam-api-%s'
                toFieldPath: metadata.name

          - name: secretmanager-api
            base:
              apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
              kind: ProjectService
              spec:
                forProvider:
                  service: secretmanager.googleapis.com
                  disableOnDestroy: false
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.environment
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'prj-%s-%s'
                toFieldPath: spec.forProvider.project
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'secretmanager-api-%s'
                toFieldPath: metadata.name

    - step: sequence-resources
      functionRef:
        name: function-sequencer
      input:
        apiVersion: sequencer.fn.crossplane.io/v1beta1
        kind: Input
        rules:
          # All *-api resources must wait for project to be ready
          - sequence:
              - project
              - .*-api
          # SharedVPC requires both project and compute-api
          - sequence:
              - project
              - sharedvpc-service-project
          - sequence:
              - compute-api
              - sharedvpc-service-project

    - step: status-handler
      functionRef:
        name: function-status-transformer
      input:
        apiVersion: function-status-transformer.fn.crossplane.io/v1beta1
        kind: StatusTransformation
        statusConditionHooks:
          # 1. Project creation errors - Extract and pass upstream
          - matchers:
              - resources:
                  - name: "project"
                conditions:
                  - type: Synced
                    status: "False"
                    reason: ReconcileError
                    message: "(?P<ErrorMsg>.*)"
            setConditions:
              - target: CompositeAndClaim
                force: true
                condition:
                  type: Developer
                  status: "False"
                  reason: ProjectFailed
                  message: "GCP Project creation failed: {{ .ErrorMsg }}"
            createEvents:
              - target: CompositeAndClaim
                event:
                  type: Warning
                  reason: ProjectFailed
                  message: "GCP project creation failed"

          # 2. SharedVPC linking errors - Extract and pass upstream
          - matchers:
              - resources:
                  - name: "sharedvpc-service-project"
                conditions:
                  - type: Synced
                    status: "False"
                    reason: ReconcileError
                    message: "(?P<ErrorMsg>.*)"
            setConditions:
              - target: CompositeAndClaim
                force: true
                condition:
                  type: Developer
                  status: "False"
                  reason: SharedVPCFailed
                  message: "SharedVPC linking failed: {{ .ErrorMsg }}"
            createEvents:
              - target: CompositeAndClaim
                event:
                  type: Warning
                  reason: SharedVPCFailed
                  message: "SharedVPC link failed"

          # 3. API enablement errors - Extract and pass upstream
          - matchers:
              - resources:
                  - name: ".*-api"
                conditions:
                  - type: Synced
                    status: "False"
                    reason: ReconcileError
                    message: "(?P<ErrorMsg>.*)"
            setConditions:
              - target: CompositeAndClaim
                force: true
                condition:
                  type: Developer
                  status: "False"
                  reason: APIEnablementFailed
                  message: "GCP API enablement failed: {{ .ErrorMsg }}"
            createEvents:
              - target: CompositeAndClaim
                event:
                  type: Warning
                  reason: APIEnablementFailed
                  message: "GCP API enablement failed"

          # 4. Success condition - All resources synced and ready (placed LAST)
          - matchers:
              - resources:
                  - name: "project"
                conditions:
                  - type: Synced
                    status: "True"
                  - type: Ready
                    status: "True"
              - resources:
                  - name: "sharedvpc-service-project"
                conditions:
                  - type: Synced
                    status: "True"
                  - type: Ready
                    status: "True"
              - resources:
                  - name: ".*-api"
                conditions:
                  - type: Synced
                    status: "True"
                  - type: Ready
                    status: "True"
            setConditions:
              - target: CompositeAndClaim
                force: false
                condition:
                  type: Developer
                  status: "True"
                  reason: ProjectReady
                  message: "GCP project fully provisioned with all APIs enabled"
            createEvents:
              - target: CompositeAndClaim
                event:
                  type: Normal
                  reason: ProjectReady
                  message: "GCP project successfully created and configured"

    - step: auto-ready
      functionRef:
        name: function-auto-ready
