apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcpproject.platform.openco.tech
spec:
  compositeTypeRef:
    apiVersion: platform.openco.tech/v1alpha1
    kind: GCPProject
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: project
            base:
              apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
              kind: Project
              spec:
                forProvider:
                  autoCreateNetwork: false
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.environment
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'prj-%s-%s'
                toFieldPath: metadata.name
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.environment
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'prj-%s-%s'
                toFieldPath: spec.forProvider.name
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.environment
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'prj-%s-%s'
                toFieldPath: spec.forProvider.projectId
              - fromFieldPath: spec.billingAccount
                toFieldPath: spec.forProvider.billingAccount
              - fromFieldPath: spec.orgId
                toFieldPath: spec.forProvider.orgId
              - fromFieldPath: spec.environment
                toFieldPath: metadata.labels[env]
              - fromFieldPath: spec.teamId
                toFieldPath: metadata.labels[team]
              - fromFieldPath: spec.costCenter
                toFieldPath: metadata.labels[cost-center]
              - type: ToCompositeFieldPath
                fromFieldPath: spec.forProvider.projectId
                toFieldPath: status.projectId
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.number
                toFieldPath: status.projectNumber

          - name: compute-api
            base:
              apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
              kind: ProjectService
              spec:
                forProvider:
                  service: compute.googleapis.com
                  disableOnDestroy: false
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.environment
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'prj-%s-%s'
                toFieldPath: spec.forProvider.project
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'compute-api-%s'
                toFieldPath: metadata.name

          - name: run-api
            base:
              apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
              kind: ProjectService
              spec:
                forProvider:
                  service: run.googleapis.com
                  disableOnDestroy: false
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.environment
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'prj-%s-%s'
                toFieldPath: spec.forProvider.project
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'run-api-%s'
                toFieldPath: metadata.name

          - name: artifactregistry-api
            base:
              apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
              kind: ProjectService
              spec:
                forProvider:
                  service: artifactregistry.googleapis.com
                  disableOnDestroy: false
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.environment
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'prj-%s-%s'
                toFieldPath: spec.forProvider.project
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'artifactregistry-api-%s'
                toFieldPath: metadata.name

          - name: iam-api
            base:
              apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
              kind: ProjectService
              spec:
                forProvider:
                  service: iam.googleapis.com
                  disableOnDestroy: false
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.environment
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'prj-%s-%s'
                toFieldPath: spec.forProvider.project
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'iam-api-%s'
                toFieldPath: metadata.name

          - name: secretmanager-api
            base:
              apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
              kind: ProjectService
              spec:
                forProvider:
                  service: secretmanager.googleapis.com
                  disableOnDestroy: false
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.environment
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'prj-%s-%s'
                toFieldPath: spec.forProvider.project
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.appName
                  strategy: string
                  string:
                    fmt: 'secretmanager-api-%s'
                toFieldPath: metadata.name

    - step: auto-ready
      functionRef:
        name: function-auto-ready
