apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-sequencer
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  package: xpkg.crossplane.io/crossplane-contrib/function-sequencer:v0.3.0
