apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-composites
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  info:
    - name: 'Purpose'
      value: 'Deploys application environment instances (Composite Resource claims)'
    - name: 'Resources'
      value: 'AppEnvironment XRs: GCP projects, Cloud Run services, Artifact Registries'
    - name: 'Target Namespace'
      value: 'argocd'
    - name: 'Sync Wave'
      value: '4 - Application instances (after platform is ready)'
    - name: 'Source Path'
      value: 'crossplane/composites/examples'
    - name: 'Environments'
      value: 'sandbox, hml, prod'
  project: default
  source:
    repoURL: https://github.com/gcopilot-openco/platform-gitops.git
    targetRevision: main
    path: crossplane/composites/examples
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
