apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-definitions
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  info:
    - name: 'Purpose'
      value: 'Defines custom platform APIs (XRDs) for self-service infrastructure'
    - name: 'Resources'
      value: 'XRDs: AppEnvironment, GCPProject, GCPCloudRun, GCPArtifact, etc.'
    - name: 'Target Namespace'
      value: 'crossplane-system'
    - name: 'Sync Wave'
      value: '2 - API definitions (after providers)'
    - name: 'Source Path'
      value: 'crossplane/definitions'
  project: default
  source:
    repoURL: https://github.com/gcopilot-openco/platform-gitops.git
    targetRevision: main
    path: crossplane/definitions
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-compositions
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  info:
    - name: 'Purpose'
      value: 'Implements platform API logic via Crossplane compositions'
    - name: 'Resources'
      value: 'Compositions: Pipeline mode with patch-and-transform + auto-ready'
    - name: 'Target Namespace'
      value: 'crossplane-system'
    - name: 'Sync Wave'
      value: '3 - Implementation layer (after definitions)'
    - name: 'Source Path'
      value: 'crossplane/compositions'
  project: default
  source:
    repoURL: https://github.com/gcopilot-openco/platform-gitops.git
    targetRevision: main
    path: crossplane/compositions
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
