apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-providers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  info:
    - name: 'Purpose'
      value: 'Installs Crossplane provider packages and configurations'
    - name: 'Resources'
      value: 'Provider (GCP, Kubernetes), ProviderConfig, function packages'
    - name: 'Target Namespace'
      value: 'crossplane-system'
    - name: 'Sync Wave'
      value: '1 - Foundation layer (deploys first)'
    - name: 'Source Path'
      value: 'crossplane/providers'
  project: default
  source:
    repoURL: https://github.com/gcopilot-openco/platform-gitops.git
    targetRevision: main
    path: crossplane/providers
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
